/**
 * @type {import('@remix-run/dev/config').AppConfig}
 */
module.exports = {
  serverBuildTarget: "netlify",
  server: "./server.js",
  ignoredRouteFiles: [".*"],
  // serverDependenciesToBundle: [
  //   // all of these dependencies are for mdx-js
  //   "@mdx-js/mdx",
  //   "unified",
  //   "bail",
  //   "trough",
  //   "vfile",
  //   "vfile-message",
  //   "unist-util-stringify-position",
  //   "remark-mdx",
  //   "micromark-extension-mdxjs",
  //   "micromark-util-combine-extensions",
  //   "micromark-util-chunked",
  //   "micromark-extension-mdx-expression",
  //   "micromark-factory-mdx-expression",
  //   "micromark-util-character",
  //   "micromark-factory-space",
  //   "unist-util-position-from-estree",
  //   "micromark-util-events-to-acorn",
  //   "estree-util-visit",
  //   "micromark-extension-mdx-jsx",
  //   "estree-util-is-identifier-name",
  //   "micromark-extension-mdx-md",
  //   "micromark-extension-mdxjs-esm",
  //   "micromark-core-commonmark",
  //   "mdast-util-mdx",
  //   "mdast-util-mdx-expression",
  //   "mdast-util-mdx-jsx",
  //   "ccount",
  //   "parse-entities",
  //   "character-entities-legacy",
  //   "character-reference-invalid",
  //   "is-decimal",
  //   "is-hexadecimal",
  //   "is-alphanumerical",
  //   "is-alphabetical",
  //   "decode-named-character-reference",
  //   "character-entities",
  //   "stringify-entities",
  //   "mdast-util-to-markdown",
  //   "mdast-util-to-markdown/lib/util/container-flow.js",
  //   "mdast-util-to-markdown/lib/util/container-phrasing.js",
  //   "mdast-util-to-markdown/lib/util/indent-lines.js",
  //   "mdast-util-to-markdown/lib/util/track.js",
  //   "mdast-util-mdxjs-esm",
  //   "remark-parse",
  //   "mdast-util-from-markdown",
  //   "mdast-util-to-string",
  //   "micromark/lib/parse.js",
  //   "micromark-util-classify-character",
  //   "micromark-util-resolve-all",
  //   "micromark-util-subtokenize",
  //   "micromark-factory-destination",
  //   "micromark-factory-label",
  //   "micromark-factory-title",
  //   "micromark-factory-whitespace",
  //   "micromark-util-normalize-identifier",
  //   "micromark-util-html-tag-name",
  //   "micromark/lib/preprocess.js",
  //   "micromark/lib/postprocess.js",
  //   "micromark-util-decode-numeric-character-reference",
  //   "micromark-util-decode-string",
  //   "remark-rehype",
  //   "mdast-util-to-hast",
  //   "unist-builder",
  //   "unist-util-visit",
  //   "unist-util-visit-parents",
  //   "unist-util-is",
  //   "unist-util-position",
  //   "unist-util-generated",
  //   "mdast-util-definitions",
  //   "micromark-util-sanitize-uri",
  //   "micromark-util-encode",
  //   "estree-util-build-jsx",
  //   "estree-walker",
  //   "periscopic",
  //   "is-reference",
  //   "hast-util-to-estree",
  //   "comma-separated-tokens",
  //   "estree-util-attach-comments",
  //   "hast-util-whitespace",
  //   "property-information",
  //   "space-separated-tokens",
  //   "zwitch"
  // ],
  // appDirectory: "app",
  // assetsBuildDirectory: "public/build",
  // serverBuildPath: "netlify/functions/server/index.js",
  // publicPath: "/build/",
  // devServerPort: 8002
};
